server:
  port: 8822


spring:
  datasource:
    dynamic:
      primary: rose
      strict: false
      datasource:
        rose:
          url: jdbc:sqlserver://10.10.10.141;databaseName=HJ_R7erp;allowMultiQueries=true
          username: sa
          password: 1qazxsw2~
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        mes:
          url: jdbc:sqlserver://47.119.139.33;databaseName=aaa;allowMultiQueries=true
          username: aaa
          password: 123
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
      cache: false
      mode: HTML
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-wait: -1
        max-active: 10
        max-idle: 10
        min-idle: 0


mybatis:
  type-aliases-package: com.honji


mybatis-plus:
    # 支持统配符 * 或者 ; 分割
    typeEnumsPackage: com.honji.enums
    configuration:
      default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
#      auto-mapping-unknown-column-behavior: warning
    global-config:
      db-config:
        update-strategy: ignored #更新所有字段

pagehelper:
  helper-dialect: sqlserver
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

http-pool:
  # 连接池最大连接数
  max-total: 100
  # 每个rount请求的最大连接数
  default-max-per-route: 20
  # 空闲多长时间（毫秒）来校验连接的有效性
  validate-after-inactivity: 2000
  # 建立连接的最大超时时间（毫秒）
  connect-timeout: 20000
  # 获取连接的最大超时时间（毫秒）
  connection-request-timeout: 20000
  # 与服务端保持连接的最大时间（毫秒）
  socket-timeout: 20000


feign:
  httpclient:
    enabled: true

logging:
  file: logs/synch.log
  level:
    com.honji.mapper: debug
    root: INFO

